#0 building with "desktop-linux" instance using docker driver

#1 [theatre-api internal] load build definition from Dockerfile
#1 transferring dockerfile: 694B done
#1 DONE 0.0s

#2 [theatre-api internal] load metadata for docker.io/library/python:3.12-slim
#2 DONE 1.1s

#3 [theatre-api internal] load .dockerignore
#3 transferring context: 1.06kB done
#3 DONE 0.0s

#4 [theatre-api 1/8] FROM docker.io/library/python:3.12-slim@sha256:85824326bc4ae27a1abb5bc0dd9e08847aa5fe73d8afb593b1b45b7cb4180f57
#4 resolve docker.io/library/python:3.12-slim@sha256:85824326bc4ae27a1abb5bc0dd9e08847aa5fe73d8afb593b1b45b7cb4180f57 done
#4 DONE 0.0s

#5 [theatre-api internal] load build context
#5 transferring context: 1.90kB done
#5 DONE 0.0s

#6 [theatre-api 2/8] RUN apt-get update && apt-get install -y curl build-essential netcat-openbsd     gcc     libpq-dev     && rm -rf /var/lib/apt/lists/*
#6 CACHED

#7 [theatre-api 5/8] COPY pyproject.toml poetry.lock ./
#7 CACHED

#8 [theatre-api 6/8] RUN poetry install --only main
#8 CACHED

#9 [theatre-api 3/8] WORKDIR /opt/app
#9 CACHED

#10 [theatre-api 4/8] RUN curl -sSL https://install.python-poetry.org | python3 -     && export PATH="/root/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"     && poetry config virtualenvs.create false
#10 CACHED

#11 [theatre-api 7/8] COPY /src .
#11 CACHED

#12 [theatre-api 8/8] RUN alembic revision --autogenerate -m "Миграция из Docker" && alembic upgrade head
#12 1.022 2025-04-16 21:28:20,811 - core.config - INFO - app_config.initialized: {"project_name":"movies","base_dir":"/opt/app","docs_url":"/api/openapi","openapi_url":"/api/openapi.json","cache_expire_in_seconds":300,"db":{"host":"localhost","port":5432,"user":"postgres","password":"postgres","db_name":"pg_db"},"elastic":{"host":"localhost","port":9200},"redis":{"host":"localhost","port":6379,"user":"redis_user","password":"Parol123","db":0},"server":{"host":"0.0.0.0","port":8000,"timeout":30,"backlog":512,"max_requests":1000,"max_requests_jitter":50,"worker_class":"uvicorn.workers.UvicornWorker"}}
#12 1.055 Traceback (most recent call last):
#12 1.055   File "/usr/local/bin/alembic", line 8, in <module>
#12 1.055     sys.exit(main())
#12 1.055              ^^^^^^
#12 1.055   File "/usr/local/lib/python3.12/site-packages/alembic/config.py", line 636, in main
#12 1.055     CommandLine(prog=prog).main(argv=argv)
#12 1.055   File "/usr/local/lib/python3.12/site-packages/alembic/config.py", line 626, in main
#12 1.055     self.run_cmd(cfg, options)
#12 1.055   File "/usr/local/lib/python3.12/site-packages/alembic/config.py", line 603, in run_cmd
#12 1.056     fn(
#12 1.056   File "/usr/local/lib/python3.12/site-packages/alembic/command.py", line 236, in revision
#12 1.056     script_directory.run_env()
#12 1.056   File "/usr/local/lib/python3.12/site-packages/alembic/script/base.py", line 586, in run_env
#12 1.056     util.load_python_file(self.dir, "env.py")
#12 1.056   File "/usr/local/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
#12 1.056     module = load_module_py(module_id, path)
#12 1.056              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#12 1.056   File "/usr/local/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
#12 1.056     spec.loader.exec_module(module)  # type: ignore
#12 1.056     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#12 1.056   File "<frozen importlib._bootstrap_external>", line 999, in exec_module
#12 1.056   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
#12 1.056   File "/opt/app/migrations/env.py", line 93, in <module>
#12 1.056     run_migrations_online()
#12 1.056   File "/opt/app/migrations/env.py", line 81, in run_migrations_online
#12 1.056     with connectable.connect() as connection:
#12 1.056          ^^^^^^^^^^^^^^^^^^^^^
#12 1.056   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3274, in connect
#12 1.057     return self._connection_cls(self)
#12 1.057            ^^^^^^^^^^^^^^^^^^^^^^^^^^
#12 1.057   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
#12 1.057     self._dbapi_connection = engine.raw_connection()
#12 1.057                              ^^^^^^^^^^^^^^^^^^^^^^^
#12 1.057   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3298, in raw_connection
#12 1.057     return self.pool.connect()
#12 1.057            ^^^^^^^^^^^^^^^^^^^
#12 1.057   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 449, in connect
#12 1.057     return _ConnectionFairy._checkout(self)
#12 1.057            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#12 1.057   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1264, in _checkout
#12 1.057     fairy = _ConnectionRecord.checkout(pool)
#12 1.057             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#12 1.057   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 713, in checkout
#12 1.057     rec = pool._do_get()
#12 1.057           ^^^^^^^^^^^^^^
#12 1.057   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 308, in _do_get
#12 1.057     return self._create_connection()
#12 1.057            ^^^^^^^^^^^^^^^^^^^^^^^^^
#12 1.057   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
#12 1.057     return _ConnectionRecord(self)
#12 1.057            ^^^^^^^^^^^^^^^^^^^^^^^
#12 1.057   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 675, in __init__
#12 1.057     self.__connect()
#12 1.057   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 901, in __connect
#12 1.058     with util.safe_reraise():
#12 1.058          ^^^^^^^^^^^^^^^^^^^
#12 1.058   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
#12 1.058     raise exc_value.with_traceback(exc_tb)
#12 1.058   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 897, in __connect
#12 1.058     self.dbapi_connection = connection = pool._invoke_creator(self)
#12 1.058                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
#12 1.058   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 646, in connect
#12 1.058     return dialect.connect(*cargs, **cparams)
#12 1.058            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#12 1.058   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 625, in connect
#12 1.058     return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
#12 1.058            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#12 1.058   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 954, in connect
#12 1.058     await_fallback(creator_fn(*arg, **kw)),
#12 1.058     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#12 1.058   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 162, in await_fallback
#12 1.058     return loop.run_until_complete(awaitable)
#12 1.058            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#12 1.058   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
#12 1.058     return future.result()
#12 1.058            ^^^^^^^^^^^^^^^
#12 1.058   File "/usr/local/lib/python3.12/site-packages/asyncpg/connection.py", line 2421, in connect
#12 1.059     return await connect_utils._connect(
#12 1.059            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#12 1.059   File "/usr/local/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 1075, in _connect
#12 1.059     raise last_error or exceptions.TargetServerAttributeNotMatched(
#12 1.059   File "/usr/local/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 1049, in _connect
#12 1.059     conn = await _connect_addr(
#12 1.059            ^^^^^^^^^^^^^^^^^^^^
#12 1.059   File "/usr/local/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 886, in _connect_addr
#12 1.059     return await __connect_addr(params, True, *args)
#12 1.059            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#12 1.059   File "/usr/local/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 931, in __connect_addr
#12 1.059     tr, pr = await connector
#12 1.059              ^^^^^^^^^^^^^^^
#12 1.059   File "/usr/local/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 802, in _create_ssl_connection
#12 1.059     tr, pr = await loop.create_connection(
#12 1.059              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#12 1.059   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1140, in create_connection
#12 1.059     raise OSError('Multiple exceptions: {}'.format(
#12 1.059 OSError: Multiple exceptions: [Errno 111] Connect call failed ('::1', 5432, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 5432)
#12 ERROR: process "/bin/sh -c alembic revision --autogenerate -m \"Миграция из Docker\" && alembic upgrade head" did not complete successfully: exit code: 1
------
 > [theatre-api 8/8] RUN alembic revision --autogenerate -m "Миграция из Docker" && alembic upgrade head:
1.059            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1.059   File "/usr/local/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 931, in __connect_addr
1.059     tr, pr = await connector
1.059              ^^^^^^^^^^^^^^^
1.059   File "/usr/local/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 802, in _create_ssl_connection
1.059     tr, pr = await loop.create_connection(
1.059              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1.059   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1140, in create_connection
1.059     raise OSError('Multiple exceptions: {}'.format(
1.059 OSError: Multiple exceptions: [Errno 111] Connect call failed ('::1', 5432, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 5432)
------
failed to solve: process "/bin/sh -c alembic revision --autogenerate -m \"Миграция из Docker\" && alembic upgrade head" did not complete successfully: exit code: 1
(venv-py3.12) kirillbogomolov@MacBook-Pro-Kirill src % docker compose up --build -d > ../output.txt 
WARN[0000] /Users/kirillbogomolov/Documents/Job/tree-of-knowledge/yandex-practicum/projects/module_3/yandex_kinoservice/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
failed to solve: process "/bin/sh -c alembic revision --autogenerate -m \"Миграция из Docker\" && alembic upgrade head" did not complete successfully: exit code: 1