Traceback (most recent call last):
  File "/Users/kirillbogomolov/Documents/Job/tree-of-knowledge/yandex-practicum/projects/module_3/yandex_kinoservice/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 103, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kirillbogomolov/Documents/Job/tree-of-knowledge/yandex-practicum/projects/module_3/yandex_kinoservice/.venv/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 350, in execute
    return super().execute(query)
           ^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near ".": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kirillbogomolov/Documents/Job/tree-of-knowledge/yandex-practicum/projects/module_3/yandex_kinoservice/services/admin-panel/src/manage.py", line 22, in <module>
    main()
  File "/Users/kirillbogomolov/Documents/Job/tree-of-knowledge/yandex-practicum/projects/module_3/yandex_kinoservice/services/admin-panel/src/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/kirillbogomolov/Documents/Job/tree-of-knowledge/yandex-practicum/projects/module_3/yandex_kinoservice/.venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/Users/kirillbogomolov/Documents/Job/tree-of-knowledge/yandex-practicum/projects/module_3/yandex_kinoservice/.venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/kirillbogomolov/Documents/Job/tree-of-knowledge/yandex-practicum/projects/module_3/yandex_kinoservice/.venv/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/kirillbogomolov/Documents/Job/tree-of-knowledge/yandex-practicum/projects/module_3/yandex_kinoservice/.venv/lib/python3.12/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kirillbogomolov/Documents/Job/tree-of-knowledge/yandex-practicum/projects/module_3/yandex_kinoservice/.venv/lib/python3.12/site-packages/django/core/management/base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kirillbogomolov/Documents/Job/tree-of-knowledge/yandex-practicum/projects/module_3/yandex_kinoservice/.venv/lib/python3.12/site-packages/django/core/management/commands/migrate.py", line 357, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "/Users/kirillbogomolov/Documents/Job/tree-of-knowledge/yandex-practicum/projects/module_3/yandex_kinoservice/.venv/lib/python3.12/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kirillbogomolov/Documents/Job/tree-of-knowledge/yandex-practicum/projects/module_3/yandex_kinoservice/.venv/lib/python3.12/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kirillbogomolov/Documents/Job/tree-of-knowledge/yandex-practicum/projects/module_3/yandex_kinoservice/.venv/lib/python3.12/site-packages/django/db/migrations/executor.py", line 255, in apply_migration
    state = migration.apply(state, schema_editor)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kirillbogomolov/Documents/Job/tree-of-knowledge/yandex-practicum/projects/module_3/yandex_kinoservice/.venv/lib/python3.12/site-packages/django/db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
  File "/Users/kirillbogomolov/Documents/Job/tree-of-knowledge/yandex-practicum/projects/module_3/yandex_kinoservice/.venv/lib/python3.12/site-packages/django/db/migrations/operations/models.py", line 97, in database_forwards
    schema_editor.create_model(model)
  File "/Users/kirillbogomolov/Documents/Job/tree-of-knowledge/yandex-practicum/projects/module_3/yandex_kinoservice/.venv/lib/python3.12/site-packages/django/db/backends/base/schema.py", line 505, in create_model
    self.execute(sql, params or None)
  File "/Users/kirillbogomolov/Documents/Job/tree-of-knowledge/yandex-practicum/projects/module_3/yandex_kinoservice/.venv/lib/python3.12/site-packages/django/db/backends/base/schema.py", line 202, in execute
    cursor.execute(sql, params)
  File "/Users/kirillbogomolov/Documents/Job/tree-of-knowledge/yandex-practicum/projects/module_3/yandex_kinoservice/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kirillbogomolov/Documents/Job/tree-of-knowledge/yandex-practicum/projects/module_3/yandex_kinoservice/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kirillbogomolov/Documents/Job/tree-of-knowledge/yandex-practicum/projects/module_3/yandex_kinoservice/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kirillbogomolov/Documents/Job/tree-of-knowledge/yandex-practicum/projects/module_3/yandex_kinoservice/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/Users/kirillbogomolov/Documents/Job/tree-of-knowledge/yandex-practicum/projects/module_3/yandex_kinoservice/.venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/kirillbogomolov/Documents/Job/tree-of-knowledge/yandex-practicum/projects/module_3/yandex_kinoservice/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 103, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kirillbogomolov/Documents/Job/tree-of-knowledge/yandex-practicum/projects/module_3/yandex_kinoservice/.venv/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 350, in execute
    return super().execute(query)
           ^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: near ".": syntax error
